export const DEAL_OVERVIEW = {
  CLEAR_FILTERS: "CLEAR_FILTERS",
  SET_BRAND_FILTERS: "SET_BRAND_FILTERS",
  SET_CATEGORY_FILTERS: "SET_CATEGORY_FILTERS",
  SET_SORT_BY: "SET_SORT_BY",
  SET_STORE_FILTERS: "SET_STORE_FILTERS",
  SET_DEALS: "SET_DEALS",
  UPDATE_DEALS: "UPDATE_DEALS"
};
