export const PRODUCTLINE = {
  SET_PRODUCT_LINE: "SET_PRODUCT_LINE",
  SET_PRODUCT_OVERVIEW_SIMPLE: "SET_PRODUCT_OVERVIEW_SIMPLE",
  SET_CURRENT_PAGE: "SET_CURRENT_PAGE",
  SET_SEARCH: "SET_SEARCH"
};
