export const SETTINGS = {
  SET_SCREEN_SIZE: "SET_SCREEN_SIZE",
  SET_BLACK_FRIDAY_DATE: "SET_BLACK_FRIDAY_DATE",
  SET_BLACK_FRIDAY_ROOT_URL: "SET_BLACK_FRIDAY_ROOT_URL",
  SET_DISTANCE_TOP: "SET_DISTANCE_TOP"
};
