export const STORE_OVERVIEW = {
  SET_SORT_BY: "SET_SORT_BY",
  SET_STATUS_FILTERS: "SET_STATUS_FILTERS",
  SET_CATEGORY_FILTERS: "SET_CATEGORY_FILTERS",
  SET_BRAND_FILTERS: "SET_BRAND_FILTERS",
  CLEAR_FILTERS: "CLEAR_FILTERS",
  SET_STORES: "SET_STORES"
};
